name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Access SECRET_NAME
        env:
          SECRET_NAME: ${{ secrets.SECRET_NAME }}
        run: echo SECRET_NAME=\"$SECRET_NAME\" > ./gradle.properties
      - name: Build the app
        run: ./gradlew assembleDebug
