name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Access SECRET_NAME
        env:
          APOD_API_KEY: ${{ secrets.SECRET_NAME }}
        run: echo SECRET_NAME=\"$SECRET_NAME\" > ./local.properties
      - name: Build the app
        run: ./gradlew assembleDebug
